version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "801:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
      - socket:/var/run
    links:
      - php

  php:
    build: ./docker/php/
    volumes:
      - ./src:/var/www/html
      - ./php.www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - socket:/var/run
    links:
      - redis

  redis:
    image: redis:latest
    volumes:
      - socket:/var/run
    ports:
      - 6379:6379

volumes:
  socket: