version: "3"

services:
  nginx:
    image: nginx:${DOCKER_NGINX_VERSION}
    ports:
      - ${DOCKER_NGINX_PORT}:80
    volumes:
      - ${DOCKER_NGINX_CONF_FILE}:/etc/nginx/nginx.conf
      - ./docker/config/default.conf:/etc/nginx/conf.d/default.conf
      - ${DOCKER_APP_PATH}:/var/www/html
      - ${DOCKER_NGINX_SITES_PATH}:/etc/nginx/sites-available
      - socket:/var/run
    links:
      - php

  php:
    build:
      context: ./docker/php
      args:
        - PHP_VERSION=${DOCKER_PHP_VERSION}
    volumes:
      - ${DOCKER_APP_PATH}:/var/www/html
      - ${DOCKER_PHP_CONF_FILE}:/usr/local/etc/php-fpm.d/zz-docker.conf
      - socket:/var/run
    links:
      - redis

  redis:
    image: redis:${DOCKER_REDIS_VERSION}
    volumes:
      - socket:/var/run
    ports:
      - ${DOCKER_REDIS_PORT}:6379

volumes:
  socket: